{% set version = '2.0-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatstat.univar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.univar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.univar/spatstat.univar_{{ version }}.tar.gz
  sha256: e8935f695ae21c4b10bf0f758e3f0995315350fd310073bf05dffdbc253c5653

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-spatstat.utils >=3.0_2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-spatstat.utils >=3.0_2

test:
  commands:
    - $R -e "library('spatstat.univar')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.univar')\""  # [win]

about:
  home: http://spatstat.org/
  license: GPL-2.0-or-later
  summary: Estimation of one-dimensional probability distributions including kernel density estimation,
    weighted empirical cumulative distribution functions, Kaplan-Meier and reduced-sample
    estimators for right-censored data, heat kernels, kernel properties, quantiles and
    integration.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
